development:
  secret_token: fdsa
  secret_key_base: 3b7cd727ee24e8444053437c36cc66c3
  some_api_key: SOMEKEY

production:
  secret_token: <%=ENV['SECRET_TOKEN_PRODUCTION']%>
  secret_key_base: <%=ENV['SECRET_KEY_PRODUCTION']%>

test:
  secret_token: some_test_secret_token
  secret_key_base: some_test_secret_key_base
